name: sync cookieclicker

on:
  schedule:
    - cron: "0 * * * *" # 1時間ごと
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 自分のリポジトリ取得
        uses: actions/checkout@v4

      - name: コピー元を取得（gh-pages）
        run: |
          git clone --depth=1 --branch gh-pages https://github.com/ozh/cookieclicker.git temp

      - name: コピー
        run: |
          rm -rf game/cookie-clicker
          mkdir -p game/cookie-clicker
          rsync -av --exclude='.git' temp/ game/cookie-clicker/

      - name: push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "auto sync" || echo "変更なし"
          git push
